[package]
name = "com"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.2.1"
lazy_static = "1.4.0"
rand = "0.8.5"
sdl2 = "0.35.2"
